# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
- ARGS="--resolver lts-4"
- ARGS="--resolver lts"
- ARGS="--resolver nightly"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script:
  - stack build --no-terminal --install-ghc
  - mkdir ./_dist
  - cp $(stack path --local-install-root)/bin/irc-GearBot ./_dist

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

addons:
    s3_region: "us-east-1"
    apt:
      packages:
      - libgmp-dev

deploy:
  provider: s3
  access_key_id: AKIAJI5U45T7ELEN2W6A
  secret_access_key:
    secure: lnigJYaSd1n7/QUQHqeICsg6stldzxl8oCf8h19zEbkwS7DvlxuE5iIptv6+i1kjq3zVHkbDv4acydNfAykqxhwgp+4P4NMFKCUR3uWoC5cvRCRkqKVcpE7CttX259soaUQnBU1tSp3FzU8ep9bbEHvRIUVO///erbNw1nuNukPxFJkmFH6CA7K8Z0YDAeSO+8TvJqaN4NRYBwHfk1NolGIuGMONdRpi00FQinRm27qHR4AmS970N00aDrT3CbNEAbE5GCAARevsgX1KWr/OiHm2UGnjlfj04Fd4A/SGD/mwb24+pjquUMHTdESTGC4oZqPQbeb8M8PCrQSM9wH7sys5myr7EfXVhSNTbp1QAe2Ruk+v9TrNprWLMRVlMPP5y7+/P0szDM1WpWPryfPxj+xqQEHmA4KTtZ1TFIHydxSHi/eABwIAjFUJCf/7LjG9kJyXn4ilyIpvwxHbU20TioO1IdxLmQsy7954bWX6pqU7HzPU/ifhEydefQnfArack94gggI6Y78uAQbzXDyAe5qzKvbqqQtsKsFqUTUmYhWEmkiyv2EY9ZSfYYrYfsCH8Jm/bubp1Bnf7KpRgpl5LeaXTQmMCBsolB/wUL/M6u9vMG4vkSfn8DmEh077Xglw6VLfJBpF+n9dY5FlKjI5mUnYw9Rlr+Z+1htf6DqB1pw=
  bucket: irc-gearbot
  local-dir: _dist
  acl: public_read
  on:
    repo: KyleOndy/GearBot-irc
